### ISSUE TITLE
Compiling your own app step 6

### ISSUE THREAD

**Issue by rajko-d** [qPCR4vir/nana-docs#2]
Add a libz.a on the list.Regards

**Comment by Pr0curo** [comment]
actually i dont understand this issue.
can you give me a hint?

**Comment by rajko-d** [comment]
When I set all those libraries in step 6. I still couldn't build nana
because of missing functions with names like inflate, deflate which are
part of libz.a libraray which is not stated in step 6.

**Comment by Pr0curo** [comment]
I did not notice any dependency on libz.a directly.
But the libpng website shows a dependency to `libz.a`.
Did you enable libpng support and built `libpng.a` by yourself?
Thats currently the only reason for the dependency I can imagine.

To prove myself I have build nana a minute ago, but even with libpng support enabled, there is no direct dependency on `libz.a`.

**Comment by rajko-d** [comment]
Step 6. is for compiling nana hello world. I made this batch file for
compiling nana:

REM First run environment_set.bat

SET NANA_SOURCE_DIR=D:\Projects\GitHub\Nana
SET NANA_BUILD_DIR=c:\Builds\Nana
SET MINGW_HOME="c:/Tools/MinGW"

IF NOT EXIST %NANA_BUILD_DIR% GOTO NO_NANA
RMDIR /s /q %NANA_BUILD_DIR%
:NO_NANA

MKDIR %NANA_BUILD_DIR%

CD /D %NANA_BUILD_DIR%

REM Although in Windows, we have to use slash ( "/" ) for paths
REM Caret ( "^" ) is for breaking long command in multiple rows
cmake -D CMAKE_CXX_COMPILER="%MINGW_HOME%/bin/g++.exe" ^
      -D CMAKE_C_COMPILER="%MINGW_HOME%/bin/gcc.exe" ^
      -D CMAKE_RC_COMPILER="%MINGW_HOME%/bin/windres.exe" ^
      -D CMAKE_MAKE_PROGRAM="%MINGW_HOME%/bin/make.exe" ^
  -D CMAKE_BUILD_TYPE=Debug ^
      -G "MinGW Makefiles" ^
  %NANA_SOURCE_DIR%

make

REM For now, later for debug and release
COPY /Y libnana.a C:\Tools\MinGW\lib

and everything compiles but when I wanted to compile hello world with
code:blocks I had to include libpng.a i libz.a which are already included
in mingw distro from nuwen.net. Maybe because I wanted cmake non-gui
approach to learn something along I did something wrong.

**Comment by Pr0curo** [comment]
Does Code::Blocks comes with its own mingw?

**Comment by rajko-d** [comment]
No, only IDE, as I can understand CMakeLists.txt if not otherwise
stated NANA_ENABLE_PNG is by default on.

**Comment by Pr0curo** [comment]
you are right, if not stated otherwise, `NANA_ENABLE_PNG` and `NANA_LIBPNG` are `ON` by default.
I'll add the libz.a to the depndency list. What really bugs me is, that i dont know why it is a needed dependency with your compilation but not with mine.

can anyone enlighten me?

best regards, jan
^
