### ISSUE TITLE
Hello World does not compile

### ISSUE THREAD

**Issue by JamesBremner** [qPCR4vir/nana-docs#5]
The _Hello World_ code presented in https://github.com/qPCR4vir/nana-docs/wiki/Hello-World does not compile.

The line

     label   lb(fm, fm.size());

gives

`C:\Users\James\code\nanatest\main.cpp|18|error: no matching function for call to 'nana::label::label(nana::form&, nana::size)'|`

The application is successful if I replace the line with

```
    label   lb(
        fm,
        rectangle(
            point(0,0),
            fm.size() ) );
```

**Comment by qPCR4vir** [comment]
Thank !
I did not find a way to embeded a cpp source file into a wiki. When the library change they get obsolete.
The correct version is continuosly tested with Travis from here:
https://github.com/qPCR4vir/nana-demo/blob/master/Examples/HelloWord.cpp
which uses a simmilar solution.
Fixing the wiki.... done!
