### ISSUE TITLE
build nana on win10-64 with codeblocks

### ISSUE THREAD

**Issue by meir100** [qPCR4vir/nana-docs#6]
in C:\nana\build\codeblocks there is an icon for codeblocks, when i try to click on it, codeblocks start and build can start, but the build gives this result:

||=== Build: Debug in nana (compiler: GNU GCC Compiler) ===|
C:\nana\source\charset.cpp|429|error: 'make_unique' is not a member of 'std'|
C:\nana\source\charset.cpp|429|error: expected primary-expression before '>' token|
C:\nana\source\charset.cpp|429|error: expected primary-expression before ')' token|
||=== Build failed: 3 error(s), 0 warning(s) (0 minute(s), 39 second(s)) ===|

**Comment by qPCR4vir** [comment]
discussed in nana forums. Not a documentation issue
