### ISSUE TITLE
"top" in div text does not work. it needs to be mentioned in doc. 

### ISSUE THREAD

**Issue by laxtools** [qPCR4vir/nana-docs#7]
I tried following code: 
```
             place layout(fm);
             layout.div("vert<top><mid><bot");
             layout.field("top") << lb1;
             layout.field("mid") << lb2;
```
where `lb1 `and `lb2 `is a label, and `fm `is a `form`. 
It shows only `lb2 `inside "`mid`" field. 

Thanks for a great gui framework.

**Comment by qPCR4vir** [comment]
Sorry, "top" is a reserverd word in place. Dont use it to name fields.
See:
https://github.com/cnjinhao/nana/blob/master/source/gui/place.cpp#L290

Feliz año nuevo !
